pull_request_rules:
  - name: ðŸš€ å½“æ‰€æœ‰æ£€æŸ¥é€šè¿‡ä¸”å®¡æŸ¥æ‰¹å‡†æ—¶è‡ªåŠ¨åˆå¹¶
    conditions:
      - base=main
      - "check-success=Netlify: Header rules - goatwiki"
      - "check-success=Netlify: Pages changed - goatwiki"
      - "check-success=Netlify: Redirect rules - goatwiki"
      - check-success=netlify/goatwiki/deploy-preview
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
queue_rules: []
