name: Build and Deploy to Netlify

on:
  push:
    branches:
      - 'main'      
      - 'master'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install mkdocs mkdocs-material
          fi

      - name: Build MkDocs Site
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gbs_offline
          path: site
          retention-days: 1

